apiVersion: v1
kind: Service
metadata:
    name: leaderboard
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: leaderboard
---
apiVersion: v1
kind: Service
metadata:
    name: web
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    selector:
        app: web
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: web
spec:
  to:
    kind: Service
    name: web
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
